// bernard-ui/src/pages/admin/History.tsx
import { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../../components/ui/card';
import { Button } from '../../components/ui/button';
import { Badge } from '../../components/ui/badge';
import { 
  Eye, 
  Trash2, 
  Play, 
  StopCircle, 
  RefreshCw,
  Search,
  Calendar,
  User,
  Clock,
  MessageSquare
} from 'lucide-react';
import { adminApiClient } from '../../services/adminApi';
import type { ConversationListItem } from '../../services/adminApi';

export default function History() {
  const [loading, setLoading] = useState(false);
  const [conversations, setConversations] = useState<ConversationListItem[]>([]);
  const [stats, setStats] = useState({ total: 0, active: 0, closed: 0 });
  const [deletingId, setDeletingId] = useState<string | null>(null);
  const [indexingAction, setIndexingAction] = useState<{ conversationId: string; action: 'retry' | 'cancel' } | null>(null);

  useEffect(() => {
    loadHistory();
  }, []);

  const loadHistory = async () => {
    setLoading(true);
    try {
      const response = await adminApiClient.listHistory({ 
        includeOpen: true, 
        includeClosed: true 
      });
      setConversations(response.items || []);
      setStats({
        total: response.total || response.items.length || 0,
        active: response.activeCount || 0,
        closed: response.closedCount || 0
      });
    } catch (error) {
      console.error('Failed to load history:', error);
      alert('Failed to load conversation history');
    } finally {
      setLoading(false);
    }
  };

  const handleDeleteConversation = async (conversationId: string) => {
    if (!confirm('Delete this conversation? This action cannot be undone.')) {
      return;
    }

    setDeletingId(conversationId);
    try {
      await adminApiClient.deleteConversation(conversationId);
      setConversations(conversations.filter(c => c.id !== conversationId));
      loadHistory(); // Refresh stats
    } catch (error) {
      console.error('Failed to delete conversation:', error);
      alert('Failed to delete conversation');
    } finally {
      setDeletingId(null);
    }
  };

  const handleCloseConversation = async (conversationId: string) => {
    try {
      await adminApiClient.closeConversation(conversationId);
      setConversations(conversations.map(c => 
        c.id === conversationId ? { ...c, status: 'closed' as const } : c
      ));
      loadHistory(); // Refresh stats
    } catch (error) {
      console.error('Failed to close conversation:', error);
      alert('Failed to close conversation');
    }
  };

  const handleRetryIndexing = async (conversationId: string) => {
    if (indexingAction) return; // Prevent multiple actions

    setIndexingAction({ conversationId, action: 'retry' });
    try {
      const result = await adminApiClient.retryIndexing(conversationId);
      if (result.success) {
        setConversations(conversations.map(c => 
          c.id === conversationId 
            ? { ...c, indexingStatus: result.indexingStatus, indexingAttempts: (c.indexingAttempts || 0) + 1, indexingError: undefined }
            : c
        ));
      } else {
        alert(result.message || 'Unable to retry indexing');
      }
    } catch (error) {
      console.error('Failed to retry indexing:', error);
      alert('Failed to retry indexing');
    } finally {
      setIndexingAction(null);
    }
  };

  const handleCancelIndexing = async (conversationId: string) => {
    if (indexingAction) return; // Prevent multiple actions

    setIndexingAction({ conversationId, action: 'cancel' });
    try {
      const result = await adminApiClient.cancelIndexing(conversationId);
      if (result.success) {
        setConversations(conversations.map(c => 
          c.id === conversationId 
            ? { ...c, indexingStatus: result.indexingStatus, indexingError: undefined }
            : c
        ));
      } else {
        alert(result.message || 'Unable to cancel indexing');
      }
    } catch (error) {
      console.error('Failed to cancel indexing:', error);
      alert('Failed to cancel indexing');
    } finally {
      setIndexingAction(null);
    }
  };

  const canRetryIndexing = (conversation: ConversationListItem): boolean => {
    const status = conversation.indexingStatus || 'none';
    return status === 'none' || status === 'failed';
  };

  const canCancelIndexing = (conversation: ConversationListItem): boolean => {
    const status = conversation.indexingStatus || 'none';
    return status === 'queued' || status === 'indexing';
  };

  const getIndexingStatusInfo = (status?: string) => {
    switch (status) {
      case 'none':
        return { label: 'Not indexed', color: 'secondary', icon: 'pi pi-circle' };
      case 'queued':
        return { label: 'Queued', color: 'info', icon: 'pi pi-clock' };
      case 'indexing':
        return { label: 'Indexing', color: 'warning', icon: 'pi pi-spin pi-spinner' };
      case 'indexed':
        return { label: 'Indexed', color: 'success', icon: 'pi pi-check-circle' };
      case 'failed':
        return { label: 'Failed', color: 'danger', icon: 'pi pi-exclamation-circle' };
      default:
        return { label: 'Unknown', color: 'secondary', icon: 'pi pi-question-circle' };
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-64">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-gray-900"></div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-gray-900 dark:text-white">Conversation History</h1>
          <p className="text-gray-600 dark:text-gray-300">Review and manage historical conversations</p>
        </div>
        <Button onClick={loadHistory} variant="outline">
          <RefreshCw className="mr-2 h-4 w-4" />
          Refresh
        </Button>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-gray-500 dark:text-gray-400">Total Conversations</p>
                <p className="text-2xl font-bold">{stats.total}</p>
              </div>
              <MessageSquare className="h-8 w-8 text-blue-500" />
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-gray-500 dark:text-gray-400">Active</p>
                <p className="text-2xl font-bold text-green-600">{stats.active}</p>
              </div>
              <Clock className="h-8 w-8 text-green-500" />
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="p-4">
            <div className="flex items-center justify-between">
              <div>
                <p className="text-sm text-gray-500 dark:text-gray-400">Closed</p>
                <p className="text-2xl font-bold text-gray-600">{stats.closed}</p>
              </div>
              <Calendar className="h-8 w-8 text-gray-500" />
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Conversations Table */}
      <Card>
        <CardHeader>
          <CardTitle>Recent Conversations</CardTitle>
          <CardDescription>
            View and manage conversation history with indexing status
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="overflow-x-auto">
            <table className="w-full table-auto">
              <thead>
                <tr className="border-b border-gray-200 dark:border-gray-700">
                  <th className="text-left py-3 px-4 font-semibold text-gray-600 dark:text-gray-300">ID</th>
                  <th className="text-left py-3 px-4 font-semibold text-gray-600 dark:text-gray-300">User</th>
                  <th className="text-left py-3 px-4 font-semibold text-gray-600 dark:text-gray-300">Date</th>
                  <th className="text-left py-3 px-4 font-semibold text-gray-600 dark:text-gray-300">Status</th>
                  <th className="text-left py-3 px-4 font-semibold text-gray-600 dark:text-gray-300">Indexing</th>
                  <th className="text-left py-3 px-4 font-semibold text-gray-600 dark:text-gray-300">Messages</th>
                  <th className="text-left py-3 px-4 font-semibold text-gray-600 dark:text-gray-300">Actions</th>
                </tr>
              </thead>
              <tbody>
                {conversations.map((conversation) => {
                  const indexingInfo = getIndexingStatusInfo(conversation.indexingStatus);
                  return (
                    <tr key={conversation.id} className="border-b border-gray-100 dark:border-gray-800">
                      <td className="py-3 px-4">
                        <div className="flex items-center space-x-2">
                          <span className="font-mono text-sm text-gray-600 dark:text-gray-300">
                            {conversation.id.substring(0, 8)}...
                          </span>
                        </div>
                      </td>
                      <td className="py-3 px-4">
                        <div className="flex items-center space-x-2">
                          <User className="h-4 w-4 text-gray-400" />
                          <span className="text-sm text-gray-600 dark:text-gray-300">
                            {conversation.tokenNames?.[0] || 'Unknown'}
                          </span>
                        </div>
                      </td>
                      <td className="py-3 px-4">
                        <div className="flex flex-col">
                          <span className="text-sm text-gray-600 dark:text-gray-300">
                            {new Date(conversation.startedAt).toLocaleDateString()}
                          </span>
                          <span className="text-xs text-gray-400 dark:text-gray-500">
                            {new Date(conversation.startedAt).toLocaleTimeString()}
                          </span>
                        </div>
                      </td>
                      <td className="py-3 px-4">
                        <Badge variant={
                          conversation.status === 'open' ? 'default' : 'secondary'
                        }>
                          {conversation.status === 'open' ? 'Active' : 'Closed'}
                        </Badge>
                      </td>
                      <td className="py-3 px-4">
                        <Badge variant={
                          indexingInfo.color === 'success' ? 'default' :
                          indexingInfo.color === 'warning' ? 'secondary' :
                          indexingInfo.color === 'danger' ? 'destructive' : 'secondary'
                        }>
                          {indexingInfo.label}
                        </Badge>
                        {conversation.indexingError && (
                          <p className="text-xs text-red-500 mt-1">
                            Error: {conversation.indexingError}
                          </p>
                        )}
                      </td>
                      <td className="py-3 px-4">
                        <span className="text-sm text-gray-600 dark:text-gray-300">
                          {conversation.messageCount}
                        </span>
                      </td>
                      <td className="py-3 px-4">
                        <div className="flex items-center space-x-2">
                          <Link to={`/admin/history/${conversation.id}`}>
                            <Button variant="outline" size="sm">
                              <Eye className="mr-2 h-4 w-4" />
                              View
                            </Button>
                          </Link>
                          
                          {conversation.status === 'open' && (
                            <Button 
                              variant="outline" 
                              size="sm"
                              onClick={() => handleCloseConversation(conversation.id)}
                            >
                              <StopCircle className="mr-2 h-4 w-4" />
                              Close
                            </Button>
                          )}
                          
                          {canRetryIndexing(conversation) && (
                            <Button 
                              variant="outline" 
                              size="sm"
                              onClick={() => handleRetryIndexing(conversation.id)}
                              disabled={indexingAction !== null}
                            >
                              <Play className="mr-2 h-4 w-4" />
                              Queue Indexing
                            </Button>
                          )}
                          
                          {canCancelIndexing(conversation) && (
                            <Button 
                              variant="outline" 
                              size="sm"
                              onClick={() => handleCancelIndexing(conversation.id)}
                              disabled={indexingAction !== null}
                            >
                              <StopCircle className="mr-2 h-4 w-4" />
                              Cancel Indexing
                            </Button>
                          )}
                          
                          <Button
                            variant="destructive"
                            size="sm"
                            onClick={() => handleDeleteConversation(conversation.id)}
                            disabled={deletingId === conversation.id}
                          >
                            <Trash2 className="mr-2 h-4 w-4" />
                            {deletingId === conversation.id ? 'Deleting...' : 'Delete'}
                          </Button>
                        </div>
                      </td>
                    </tr>
                  );
                })}
                
                {conversations.length === 0 && (
                  <tr>
                    <td colSpan={7} className="py-8 px-4 text-center text-gray-500 dark:text-gray-400">
                      No conversations found.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}

// .admin/src/app/features/history/history.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, DestroyRef, inject, signal } from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { finalize } from 'rxjs';
import { ButtonModule } from 'primeng/button';
import { TableModule } from 'primeng/table';
import { TagModule } from 'primeng/tag';
import { MessageModule } from 'primeng/message';
import { DialogModule } from 'primeng/dialog';
import { type MenuItem } from 'primeng/api';
import { MenuModule, type Menu } from 'primeng/menu';
import { Router } from '@angular/router';

import { API_CLIENT, ApiClient } from '../../data/api.service';
import { ConversationListItem } from '../../data/models';

@Component({
  selector: 'app-history',
  imports: [CommonModule, TableModule, ButtonModule, TagModule, MessageModule, DialogModule, MenuModule],
  templateUrl: './history.component.html',
  styleUrl: './history.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class HistoryComponent {
  private readonly api = inject<ApiClient>(API_CLIENT);
  private readonly router = inject(Router);
  private readonly destroyRef = inject(DestroyRef);

  readonly conversations = signal<ConversationListItem[]>([]);
  readonly loading = signal<boolean>(true);
  readonly error = signal<string | null>(null);
  readonly stats = signal<{ total: number; active: number; closed: number }>({
    total: 0,
    active: 0,
    closed: 0
  });
  readonly deletingId = signal<string | null>(null);
  readonly closingId = signal<string | null>(null);
  readonly confirmVisible = signal<boolean>(false);
  readonly pendingConversation = signal<ConversationListItem | null>(null);
  readonly indexingActionInProgress = signal<{ conversationId: string; action: 'retry' | 'cancel' } | null>(null);

  constructor() {
    this.load();
  }

  load() {
    this.loading.set(true);
    this.api
      .listHistory({ includeOpen: true, includeClosed: true })
      .pipe(
        takeUntilDestroyed(this.destroyRef),
        finalize(() => this.loading.set(false))
      )
      .subscribe({
        next: (value) => {
          this.conversations.set(value.items ?? []);
          this.stats.set({
            total: value.total ?? value.items.length ?? 0,
            active: value.activeCount ?? 0,
            closed: value.closedCount ?? 0
          });
          this.error.set(null);
        },
        error: () => this.error.set('Unable to load history')
      });
  }

  open(conversation: ConversationListItem) {
    void this.router.navigate(['/history', conversation.id]);
  }

  navigateFromKey(event: Event, conversation: ConversationListItem) {
    if (!(event instanceof KeyboardEvent)) {
      return;
    }
    if (event.key !== 'Enter' && event.key !== ' ') {
      return;
    }
    event.preventDefault();
    this.open(conversation);
  }

  statusLabel(status: ConversationListItem['status']) {
    return status === 'open' ? 'Active' : 'Closed';
  }

  hasErrors(conversation: ConversationListItem): boolean {
    return conversation.hasErrors ?? ((conversation.errorCount ?? 0) > 0);
  }

  messageCount(conversation: ConversationListItem): number {
    return conversation.userAssistantCount ?? conversation.messageCount ?? 0;
  }

  indexingStatusLabel(status?: ConversationListItem['indexingStatus']): string {
    switch (status) {
      case 'none': return 'Not indexed';
      case 'queued': return 'Queued';
      case 'indexing': return 'Indexing';
      case 'indexed': return 'Indexed';
      case 'failed': return 'Failed';
      default: return 'Unknown';
    }
  }

  indexingStatusSeverity(status?: ConversationListItem['indexingStatus']): 'success' | 'warning' | 'danger' | 'info' | 'secondary' {
    switch (status) {
      case 'none': return 'secondary';
      case 'queued': return 'info';
      case 'indexing': return 'warning';
      case 'indexed': return 'success';
      case 'failed': return 'danger';
      default: return 'secondary';
    }
  }

  indexingStatusIcon(status?: ConversationListItem['indexingStatus']): string {
    switch (status) {
      case 'none': return 'pi pi-circle';
      case 'queued': return 'pi pi-clock';
      case 'indexing': return 'pi pi-spin pi-spinner';
      case 'indexed': return 'pi pi-check-circle';
      case 'failed': return 'pi pi-exclamation-circle';
      default: return 'pi pi-question-circle';
    }
  }

  canRetryIndexing(conversation: ConversationListItem): boolean {
    const status = conversation.indexingStatus ?? 'none';
    return status === 'none' || status === 'failed';
  }

  canCancelIndexing(conversation: ConversationListItem): boolean {
    const status = conversation.indexingStatus ?? 'none';
    return status === 'queued' || status === 'indexing';
  }

  isIndexingActionAvailable(conversation: ConversationListItem): boolean {
    return this.canRetryIndexing(conversation) || this.canCancelIndexing(conversation);
  }

  formatLatencyMs(value: number | undefined | null): string {
    if (value === null || value === undefined || Number.isNaN(value)) return '—';
    if (value < 1000) return `${value} ms`;
    const seconds = value / 1000;
    if (seconds < 60) return `${seconds.toFixed(seconds >= 10 ? 1 : 2)} s`;
    const minutes = Math.floor(seconds / 60);
    const remainingSeconds = Math.round(seconds - minutes * 60);
    return remainingSeconds ? `${minutes}m ${remainingSeconds}s` : `${minutes}m`;
  }

  menuItems(conversation: ConversationListItem): MenuItem[] {
    const disabled = this.deletingId() === conversation.id || this.closingId() === conversation.id;
    const items: MenuItem[] = [
      {
        label: 'Delete',
        icon: 'pi pi-trash',
        disabled,
        command: () => this.promptDelete(conversation)
      }
    ];

    if (this.canRetryIndexing(conversation)) {
      items.push({
        label: 'Queue for Indexing',
        icon: 'pi pi-play',
        disabled: disabled || this.indexingActionInProgress() !== null,
        command: () => this.retryIndexing(conversation)
      });
    }

    if (this.canCancelIndexing(conversation)) {
      items.push({
        label: 'Cancel Indexing',
        icon: 'pi pi-stop',
        disabled: disabled || this.indexingActionInProgress() !== null,
        command: () => this.cancelIndexing(conversation)
      });
    }

    return items;
  }

  retryIndexing(conversation: ConversationListItem) {
    if (this.indexingActionInProgress() !== null) return;

    this.indexingActionInProgress.set({ conversationId: conversation.id, action: 'retry' });
    this.api
      .retryIndexing(conversation.id)
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: (result) => {
          if (result.success) {
            this.conversations.update((current) =>
              current.map((item) =>
                item.id === conversation.id 
                  ? { ...item, indexingStatus: result.indexingStatus, indexingAttempts: (item.indexingAttempts ?? 0) + 1, indexingError: undefined }
                  : item
              )
            );
          } else {
            this.error.set(result.message || 'Unable to retry indexing');
          }
        },
        error: () => this.error.set('Unable to retry indexing'),
        complete: () => this.indexingActionInProgress.set(null)
      });
  }

  cancelIndexing(conversation: ConversationListItem) {
    if (this.indexingActionInProgress() !== null) return;

    this.indexingActionInProgress.set({ conversationId: conversation.id, action: 'cancel' });
    this.api
      .cancelIndexing(conversation.id)
      .pipe(takeUntilDestroyed(this.destroyRef))
      .subscribe({
        next: (result) => {
          if (result.success) {
            this.conversations.update((current) =>
              current.map((item) =>
                item.id === conversation.id 
                  ? { ...item, indexingStatus: result.indexingStatus, indexingError: undefined }
                  : item
              )
            );
          } else {
            this.error.set(result.message || 'Unable to cancel indexing');
          }
        },
        error: () => this.error.set('Unable to cancel indexing'),
        complete: () => this.indexingActionInProgress.set(null)
      });
  }

  closeConversation(conversation: ConversationListItem) {
    if (this.closingId() === conversation.id) return;

    this.closingId.set(conversation.id);
    this.api
      .closeConversation(conversation.id)
      .pipe(
        takeUntilDestroyed(this.destroyRef),
        finalize(() => this.closingId.set(null))
      )
      .subscribe({
        next: (updated) => {
          this.conversations.update((current) =>
            current.map((item) => (item.id === conversation.id ? { ...item, ...updated, status: 'closed' } : item))
          );
          this.stats.update((current) => ({
            total: current.total,
            active: conversation.status === 'open' ? Math.max(0, current.active - 1) : current.active,
            closed: conversation.status === 'open' ? current.closed + 1 : current.closed
          }));
          this.error.set(null);
        },
        error: () => this.error.set('Unable to close conversation')
      });
  }


  promptDelete(conversation: ConversationListItem) {
    this.pendingConversation.set(conversation);
    this.confirmVisible.set(true);
  }

  cancelDelete() {
    this.confirmVisible.set(false);
    this.pendingConversation.set(null);
  }

  confirmDelete() {
    const conversation = this.pendingConversation();
    if (!conversation) {
      this.cancelDelete();
      return;
    }
    this.deletingId.set(conversation.id);
    this.api
      .deleteConversation(conversation.id)
      .pipe(
        takeUntilDestroyed(this.destroyRef),
        finalize(() => {
          this.deletingId.set(null);
          this.confirmVisible.set(false);
          this.pendingConversation.set(null);
        })
      )
      .subscribe({
        next: () => {
          this.conversations.set(this.conversations().filter((c) => c.id !== conversation.id));
          this.stats.update((current) => ({
            total: Math.max(0, current.total - 1),
            active: conversation.status === 'open' ? Math.max(0, current.active - 1) : current.active,
            closed: conversation.status === 'closed' ? Math.max(0, current.closed - 1) : current.closed
          }));
          this.error.set(null);
        },
        error: () => this.error.set('Unable to delete conversation')
      });
  }
}
